### ISSUE TITLE
Warning agora-rtc-sdk-ng dependencies on CommonJS or AMD

### ISSUE THREAD

**Issue by NarHakobyan** [saeb-panahifar/ngx-agora-sdk-ng#1]
Hi, is it possible to fix this warning?

Warning: agora.service.ts depends on 'agora-rtc-sdk-ng'. CommonJS or AMD dependencies can cause optimization bailouts.

**Comment by saeb-panahifar** [comment]
Hey @NarHakobyan. Which version of Angular you are using ?

**Comment by saeb-panahifar** [comment]
I just checked it out in both v9 and v11. There is no warning in library. @NarHakobyan

**Comment by NarHakobyan** [comment]
![image](https://user-images.githubusercontent.com/1781506/99783145-7ae3ad80-2b33-11eb-972d-7ecf1fba652f.png)

We are using angular version ^11.0.0

**Comment by saeb-panahifar** [comment]
`import { NgxAgoraSdkNgService } from 'ngx-agora-sdk-ng';` Are you using this line of code for importing ? 

The library that I have developed is not a CommonJS module. It's normal Angular library.

I hope this link will useful for you. To disable these warnings, you can add the CommonJS module name to allowedCommonJsDependencies option in the build options located in angular.json file. https://angular.io/guide/build#configuring-commonjs-dependencies.


```
"build": {
  "builder": "@angular-devkit/build-angular:browser",
  "options": {
     "allowedCommonJsDependencies": [
        "lodash"
     ]
     ...
   }
   ...
},
```
